apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.upgrade.cattle.io
spec:
  group: upgrade.cattle.io
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    singular: plan
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                concurrency:
                  type: integer
                  minimum: 1
                cordon:
                  type: boolean
                drain:
                  type: object
                  properties:
                    deleteLocalData:
                      type: boolean
                    force:
                      type: boolean
                    gracePeriod:
                      type: integer
                    ignoreDaemonSets:
                      type: boolean
                    timeout:
                      type: string
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                prepare:
                  type: object
                  properties:
                    args:
                      type: array
                      items:
                        type: string
                    command:
                      type: array
                      items:
                        type: string
                    envFrom:
                      type: array
                      items:
                        type: object
                    image:
                      type: string
                secrets:
                  type: array
                  items:
                    type: object
                serviceAccountName:
                  type: string
                tolerations:
                  type: array
                  items:
                    type: object
                upgrade:
                  type: object
                  properties:
                    args:
                      type: array
                      items:
                        type: string
                    command:
                      type: array
                      items:
                        type: string
                    envFrom:
                      type: array
                      items:
                        type: object
                    image:
                      type: string
                version:
                  type: string
                channel:
                  type: string
            status:
              type: object
              properties:
                applying:
                  type: array
                  items:
                    type: string
                conditions:
                  type: array
                  items:
                    type: object
                latestHash:
                  type: string
                latestVersion:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .status.latestVersion
        - name: Channel
          type: string
          jsonPath: .spec.channel
