---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: system-upgrade
spec:
  encryptedData:
    address: AgAj/ETsJBbe1UBwp5AjeoHBX6s6RGBLncO1BCiNHhOKq6YEPIqN6jqI7Sq/VUWqm1rfyuYayDscOF84Fe1oIFNETWb/O41mowM5pgiORNf7MhH/kAKNZgpNqFk4RkwqU5BrIg76lPwf9L+30z33fGygABHxFhTFj/LBlGH8b+FLBXK6PaeE3k4JbiWZLygrvUcTtDLSRqT8/uRclfh5lAyhuAgt00e2rm/rleoUdwQjZKk/E/oasHSNKHIj1A6kQDFakauWNlS8SHhK6ZgBQVUvYQE/6EabDG7AGPpDfZhGi/M+by5UAQv3qjmBBUKHXab6MusPADUO8wkDyGX/rl5jK7Z10glylckZKh2bgigKZd3rOfnbNvl0GLKCLpC3bavnynxkd0Qrk0PI44HyY1xYNeGp8E573U4hxLopZRH7Oo4nEVJo9U2/dBqdrMP+jrVPrFeNeKTrAIhnUc5a4l9++5fQmpawmOqyCteEbRR5jY1iCqM5dzGSdARdE/JG7hBzAibhXWG4EFg18YDhgGjwvK5ijoVy87S5/IrcxgHPd+8fzinDLQIFFJgbhKzXzrTQFEZZKBBqSVrgxtuubqZ/HdRNb+9CvvDHmLkxBGxrknK3kE4fWtTv9/VTQqzIZK4s1pCMpstqREFxcK8mlgnr+S9lsbDPYTRHICz4T4KvM5PFS1eUat/0OAFlzOmzDH+HFy/0XNq1UQWiGmACy8TqJWY1kMMLPZchjdDnR/ditDEotAHciH9yxv5QB0gSWGMAVCGp7wcCJCHXAYn97EDmIi5FWe4MNr+LjcwZqaxerSFzczlHyziwwHdvoqlL5c4meUtNLlVkHoLSuaxEmasZlcsVSwn/uBL8
  template:
    metadata:
      name: discord-webhook
      namespace: system-upgrade
