---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: system-upgrade
spec:
  encryptedData:
    address: AgB8hsEujEzj9C+oFL5Qf7Gtw4q0jGzDe1EuOIVmhYbgVONESeOpCM0vzETZjHywUepQ6jR186AotPS+j2cMzc1arZcr+jaczRAtaibHiEaf159MiZxT49jW8ytnx9qL069f4Zg9r8OHRVSwWVgkUCi5RsUwfs50ibsnudiS8TPgqSZe1iytyo6OBWlCDmXXDtL546TG54IDPNG7EUs5qRR/2FXg5ruaRwJn0Fv+MxCjBFwwQAatF9qNTZULUjVUl8rFek5BtKK29BzQ/ymj/kPXUbKp0IZlkQJ2VvizX7EU5Y3M1p6IbahD2h0h1AUvTqzdcT61O+p9SpJ7tBFAW6NgDSGanUiyjAcmiZ/upfkmQvvp+DCxkSjemKh5Y15Ak3hj0JmUFciz8hDavE3d0MYj9TGi8EmrJD8TUmm+XIM+Y19OX2J2cUvHEJ4qxzi/UAsgC7fJu/a3J6WrENen2KKdp8Lav464dEYNJzqDdiWZXNsLHBsetb20HLZG33TX2/EUX57Si1L1I3zwWO9SlaYBXyu9BrMH+0itFTjJuArrm3vupTE7jpx/5F5MndCKsAEGLunJLiVuMRFiejfKhxXiY+yUzBvtPTW376QewuUtMsTM7TBstcAtnxGW6Oh8QrGUFUQHP7pW87uBkQZTOnSMqKXhAN96KWiRbTGWvUYaEXWPaiMSsCqq4SM6C2+LprPiMNy6xhjYV6Lsdty2xYQtKu4SCqKgnP0WdRtesRyfjyivt0Xp2sWax4gMWQILYm6bJAIysZ5RcXFkKNlDu7iS1LKXaTIXGggRQgNBBkEM/CU+ieCIrcKxgouwF3oXnBWF44v4JpR72scYwBF1k06qaZhehGWoP/y2
  template:
    metadata:
      name: discord-webhook
      namespace: system-upgrade
