---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickerlake
  namespace: tickerlake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickerlake
  template:
    metadata:
      labels:
        app: tickerlake
    spec:
      containers:
        - name: tickerlake
          image: ghcr.io/major/tickerlake:latest@sha256:8b4b2bc4da2c8a812ac88cd6528da2555f93ac91b9e654acb864fdedc454f8cd
          ports:
            - containerPort: 8001
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
