---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seaweedfs-s3-credentials
  namespace: seaweedfs
spec:
  encryptedData:
    seaweedfs_s3_config: AgBAEWEL8SkBQska1OrGmTYcyfxpXLco2V6YpnrFearwz2qCoG90ZOytoS0Lt6SAmut65+fhN2GVK2jXSJkkBjLO668SBS9Fz8YCOv26p9q47vvxMYgE/TextV3zGjwMzfdPxT7g1YzVslG4D6WfGXdATS1QM2xcfxs9ApvBcEnkyPz5K5e3O/uQObCc1MWHFoclPgCsuIQeSsxufAARTUqSi+0hPwFf4/6Ij05UVTbQ34PLDZC2ABjR7GeYwUTtda8/qxyiLPKrEcKyDqVWBPLe7A52IAM6b9nvUhKvYyPlLUXZnCgd7eIywdFINrlvCswQCRU+fwJ0A0L5j+DZr1Bxg1xZV6ygk4hVak3A13xLVefSH/Jpd8dajztE2Zl9CR+monJdFtH+4JUDzEeYeTrAzsChSsBEmM+wM/WK3Qf+aCFRK2CKVvWcr/GOZ3bMe+LLDvrQPfwcUVenpX5KsofjDRG0cX+vJjT8VYcapJx5YhVaSe5EwzTBV9rtq5aKJp6/5x/7CyXQojsWd9ZQmV+NNq29ZW+WLn4VDgluY+exEtmrWqBjKVzWQ2IDGysBQg1+gNTDG2/BRSXQwEDAKW8T+X3Z8s73ssVFXEFYBwDpDy6qi4avlydW8yISVJrEIflIWIQqM3QtS3JS8525OukcUfG6ffVrYB3tJYCKEsd9hmNpWTGutlkyEIm55p28uPHt+Lothjo6TLl0xKtIqSMmTeG9v58TWpbfLQWPffJ4TSRkM0BGea+Us/ZW0mx3KDBkV34R0dVQfws3Yvf6Zp1zekrvjmuqtm5eXL12RpPWOvovrcL9+/cNqBTQL3KRqBECL0K4QCz8+GCHoJ0TJ19Z+4tQjIAf4rwIvt+e81oKEdZ5cmoUdxm6LqGp85DvxlTsBabiBaacX85t70T6z6DNTkelwp6EQja6K3mSWW96DtZ7uD9zkUUblqBDSblyLDf1OokhGxuhtpC0iJ9sP/aD6b8Z/WvPr/Y9Dr0c1cX8dj8Pqr5LweksjXWOhI++FmEzLZELtHaY97bw83U4ggR9WvrNtF+1oteiyWPAx266arLS1MIt/2Xg0L4FWEELSYU=
  template:
    metadata:
      name: seaweedfs-s3-credentials
      namespace: seaweedfs
    type: Opaque
