---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kwatch-config
  namespace: kwatch
spec:
  encryptedData:
    config.yaml: AgBi/L2Pd1EVs34eDYA6JqUErvge+wX3qJIaPXCstDM8G2uGOBV60CaJyTDORrDz1dT+5o5NSPUSpMNf2J1O51acz9mzEBgsgnhy0pW9SzNtdK01BQYuvDfHkZLesNuBse5V9eh36UvgSpgzGe6xefNSEBUgstu/83fBOr9CxttuhTGNgn4DKYFlAI/HAkpV1fWqmuhsGg3JbTWwoc4b4UBVQ+6XRfaF+NliK+Tg7ZCThhc8QVJE8EcHbmgHGawzvOwPc7eXvIkwVYCH+K+OGBu/G92gY07sTv4OpdPfN9XFI6H2Ro0Q8ZJ6hiwkLwzpXToBSBaBeTsVL+ckQRybBU/oKvEkeofhD6XJYdByAnpab4TjgYt99yBSUbduTFXKiIz/HDvvo63SZ2u0EUy8HpJuB6TzcpZQGGOLphbApM+EVxTClu7N7KLIK66u/DZqtSUKR4yYdcoggvLo+em+R3/3PurfgBmTGGqmstQnq329BfOmtfBIpc0Q3dzGBXWm67FRqbe7gcnFguR8vDAliyFXhjLfnBqchpYP9ADxR5Na/LhgmI8yfLgNRtcmi8Z5e0XMHt/tAngdZGGhptfo85lQx5XW2VL+GnqNEsj+G/jHXntZnKQmxEFZnZmFjFIgcV7UET5gqOKzNwPLKcmb6ZB4OIDWjejAYkE9XR06vpkk4nI6VgIi1itrJkjNyZvuzRLYoN3FJDPHuLBBVjPalfDR5Vt+yyXxrfPOBqmFsoNyO0klGwFlYk4s+gJKTOagidziIt8b/a18JRjJOTk1Zs8MlYTov1t8ZTwhsVD5IHjsaphhpqzUuKwjp5dGGU3/qPKGM3bzgS7Rbd7JdXZdxnRvWJif690anaM6XEMa5ENqNIYjP3i++F3T57gDS4crslSPB97NVYvpmtnxJuvgYz6e3JkU7KmWuiYbrHppCAZRKdjlF6Db7GYEkJvBjg+rFetJXWoiPdf9sapHYEvRMR3d0I/21VEgymE11UdqHR9KmqtSlTwdHzqNZY2ZQTVdfoSya8hrzCQZP92nqAsHGi8ePnOskNhgjRXIDd0k9Q6oNBxP7qKllAtP05g684R6OaKDRFvGSBbRzNHLf+bLbVQ1htQkBA==
  template:
    metadata:
      name: kwatch-config
      namespace: kwatch
