---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/infra/cloudnative-pg
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: bootstrap-infra
  # Health checks to ensure CNPG operator is fully operational
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudnative-pg
      namespace: cnpg-system
