---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/infra/envoy-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-config
    - name: gateway-api-crds
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: envoy-gateway
      namespace: envoy-gateway-system
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: amajor-cloud-gateway
      namespace: envoy-gateway-system
  timeout: 5m
