---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/postgres
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: cloudnative-pg  # Wait for CNPG operator to be ready
    - name: infra           # Wait for nginx-ingress (for TCP passthrough)
  # Health checks to ensure PostgreSQL cluster is ready
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres
      namespace: postgres
