---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: postgres
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:5.4.1@sha256:bf7ea9bd62afd2d34045b4098ad68feb4a08ad9f75f28dc5d9b7d6d84d63005c
          ports:
            - containerPort: 8080
              name: http
          env:
            # Set design to a nicer theme
            - name: ADMINER_DESIGN
              value: "pepa-linha"
            # Default server (can be overridden in UI)
            - name: ADMINER_DEFAULT_SERVER
              value: "postgres-rw"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
