---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: postgres
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:5.4.1@sha256:b1d44e230bed34ff218882f2884e1e78f9659d968d3230a3974d9018172783ea
          ports:
            - containerPort: 8080
              name: http
          env:
            # Default server (can be overridden in UI)
            - name: ADMINER_DEFAULT_SERVER
              value: "postgres-rw"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
