---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1

  # Storage configuration
  storage:
    size: 20Gi
    storageClass: local-path  # K3s default storage class

  # Bootstrap configuration - creates initial database and users
  bootstrap:
    initdb:
      database: app
      owner: appuser
      secret:
        name: postgres-app-user  # Secret for appuser password

  # Superuser secret
  superuserSecret:
    name: postgres-superuser  # Secret for postgres superuser password

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2621kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

    # Client authentication configuration
    pg_hba:
      # Allow connections with SSL from anywhere
      - host all all all scram-sha-256

  # Monitoring (can be enabled later with Prometheus)
  monitoring:
    enabled: false

  # Resource limits
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
