---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1

  # Storage configuration
  storage:
    size: 20Gi
    storageClass: local-path  # K3s default storage class

  # Enable superuser access
  enableSuperuserAccess: true

  # Superuser secret
  superuserSecret:
    name: postgres-superuser  # Secret for postgres superuser password

  # TLS certificate configuration for external access
  certificates:
    serverAltDNSNames:
      - postgres.amajor.cloud

  # Managed services - expose PostgreSQL externally via LoadBalancer
  managed:
    services:
      additional:
        - selectorType: rw  # Read-write service
          serviceTemplate:
            metadata:
              name: postgres-lb
            spec:
              type: LoadBalancer
              ports:
                - name: postgres
                  port: 5432
                  protocol: TCP
                  targetPort: 5432

  # Bootstrap configuration - use default postgres database
  bootstrap:
    initdb:
      database: postgres
      owner: postgres

  # PostgreSQL configuration (optimized for 8Gi memory)
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "2GB"                    # 25% of RAM
      effective_cache_size: "6GB"              # 75% of RAM
      maintenance_work_mem: "512MB"            # For VACUUM, CREATE INDEX
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "20MB"                         # (RAM - shared_buffers) / (max_connections * 3)
      min_wal_size: "2GB"
      max_wal_size: "8GB"
      max_worker_processes: "8"                # Match CPU limit
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"

    # Client authentication configuration
    pg_hba:
      # Require SSL for all connections from anywhere
      - hostssl all all all scram-sha-256

  # Resource limits
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "8000m"
