---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgBLymYxAlGA3jNeePAmGMc/HWe0bTAVfHtpvuQXrQkqKqsthtkilqnSK8N7ZTsX8n5n5ctlHFyyZoji80R2mpNz2BTH15l23u3HWgdP8EIjbgF5/o8jHz9kJH9yRES4qeP2QE2f/EcqCrAskdARgtDhEp/lEn844+iT6ieVE8eZ+3bubYMa6I8Jh3FIrUjpt0O/m1hT5KXfKqzaj3GGtFdIC6Egfo2fzV2iZYgcKcEj+1eIiLNe7vod1baPwux6Hcc/hhvNh8ZjPTLeLAwUpicKOOx+Ak1SNXyzI9hgOvfO96o9kY2i260IaLmaGooX4g1zlfkxeXcUJRXb9WrPIXzKTdE9uy/9iRJv8reAQIfK+Hb/xfClgd1Lbn2KihbIDPQs6CEG0ErFposj3gQ1bmfBbQ1n4yIHa7jvAxU7MrbGZ9tJ25L5JE8AnvlWID8uIuVwsEJ8iEwvCf6ELe4nb6xY/e4DmGTD35kSHwAQoFmIGEgKU5OQ/ePG1RMF9aldIh/6hH/mmEK0mK1K72BF9cYMmEViXMuYzXlbxwIjHi5Dby0L+Ou4oQ1qKtpJlvcy9iIBMBVCJ3TscsTuVjI4u9B5u6Y+PIuik3mKY78jSRfYVrCm9rTEMqbFVAmScZKQLiVCowIQLonlRN75bXZ3lWwCmba1kzdlmaeRxV3qYpNexuSxOqDsXeFnFaDfDagLYxmg7lj36Soaax4gbJxq9uItOD+y/O9k/yEHHFxUVMyLib8tjZfb2CV/nrVSiw==
    username: AgADCm9ixMGj131SOwdz7RRAbsMcEDUlV8U0umrXBVtlfUQXCmoghFUkCwUvRtpaictUbcnt2Lh+sGpEsBJspkAd85YS0plrl2QGDu7u5RboFEAJHaF+CsM25WkjyIQT33g0DM62buMYFl5EE9b7ElU7MyhFznHsJvS7IY5FBKyRMV/9yIEx632TOJgmo+77Pl8l0DwWvVgktj5sar8SAYlYbj0C4VViOaB2LO97ogEWJjGT4gFIzfXtd/Af2h7kFpzMpwx7ZzpfrW/EXsLcy5wMQIdHzQ9iHipMLNRNpXHruSZA1OUnsIadk4IaUFhMJ0iRNN399w1KjTQJ2VNxfUpgKDza7rICMUI7Pc1+TBQCFjhqpiOFBHBtIaYyILfYMJkkCrc7F8LpC6U+Ve7awoNQg77YnhhmXwKUi1Ath97hrWwS3A16iW6aNP6OumCsahD+dKP4tKyOkCcTrj1/X6LX9w6qd/HnN2bQYvyjigLfXHPetD5kzoBD6TXS1yljPbJfH63YmQjTPzW3Psr060bwoYD3Z5o+DnwPfuFbwfKDIcaliLZJIl+y3QQaoLua3PXSjR8bFd9jEzY/18/q8y3Z8tmynx2MXSGoZYJpdfIaIUtC5B0djjV7QncqMyHDdTeccQZm+J8Vh5AZTnz/O0fpI3SrV7XD95osa0D5uOWvB4vSkx0IL3xGVs4ZCE6axR6TrRq5Wx2aKQ==
  template:
    metadata:
      name: postgres-superuser
      namespace: postgres
    type: Opaque
