apiVersion: v1
data:
  identity: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JRzJBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQklHZU1JR2JBZ0VCQkRBdmNrYjJSdVhFU2svYWc0a2YKY2FucGNXMnRXY05MeFhobm9lcndmZEpUL01JOWtSeXY0dXlYNlNzQisxSHZkWCtoWkFOaUFBU0FEZmFtU2dJNwpwQjliM1ZySG5hem05OWh0UmdsZndWSlkrUmgrR3B4VGhXNkhKRWczeFJvWGhTbmxvRUZZL0JTaGkrVkFiUlJmCjZLTlJPdExBcExuNnF5UyszejRkUVhiT2lFOVBidUpvQ3U5M0h3a2xqOHhPdXU5empYNnZpeHc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  identity.pub: ZWNkc2Etc2hhMi1uaXN0cDM4NCBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF6T0RRQUFBQUlibWx6ZEhBek9EUUFBQUJoQklBTjlxWktBanVrSDF2ZFdzZWRyT2IzMkcxR0NWL0JVbGo1R0g0YW5GT0Zib2NrU0RmRkdoZUZLZVdnUVZqOEZLR0w1VUJ0RkYvb28xRTYwc0NrdWZxckpMN2ZQaDFCZHM2SVQwOXU0bWdLNzNjZkNTV1B6RTY2NzNPTmZxK0xIQT09Cg==
  known_hosts: Z2l0aHViLmNvbSBlY2RzYS1zaGEyLW5pc3RwMjU2IEFBQUFFMlZqWkhOaExYTm9ZVEl0Ym1semRIQXlOVFlBQUFBSWJtbHpkSEF5TlRZQUFBQkJCRW1LU0VOalFFZXpPbXhrWk15N29wS2d3RkI5bmt0NVlScllNak51RzVOODd1UmdnNkNMcmJvNXdBZFQveTZ2MG1LVjBVMncwV1oyWUIvKytUcG9ja2c9
kind: Secret
metadata:
  creationTimestamp: "2025-10-07T02:28:33Z"
  name: flux-system
  namespace: flux-system
  resourceVersion: "740"
  uid: 15f3061b-226f-43d9-8cfb-d9b0d3d586df
type: Opaque
