---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stockchartsalerts-secrets
  namespace: stockchartsalerts
spec:
  encryptedData:
    discord-webhook-urls: AgB3BdL7klMg2mxiyZ5MAp3jhFlL3sQFOsT467q5CGyRyIcMSTRPpKFzw/S8dZmZKFjOcXlB8X6ohbQx20pwfSDxwzNLp1lwt12IZaZ/66X16MYSfUzcSA1OKHtMgZSEWbcQGwh6hyuLI88nz4QQRwUF+EnvRIdeEttquKlhV1wfHgj87BhEZcS1M3bIEQnUWUhWatgPEhYAjpF4is2UFTCAy4CH4acMoSBbgN30s00b+pYsAP1+NQiWqKVZ12LL2Q0zq0pgo+A3cxMqirfOwQ2SfrW4x6RSbLHaxWX7A4ZjR+2dElCBNW+82MC8bEGFjQk1unWt8VvluyYa9Wj3NVwRLHT2F6Q/8WWwpSzcaMPsH1ESTzB3sVWOiKOvA3WTGGPEs7gFkxNfsQGWu6fVr5SLEjfpwRkQwEOBTAs2rU7yYnoEfM0TAm11H14pm9yNj5c4l9gkVd8WFxA5xG909e7NHOvt8je7RNnpjWjSTQ1WSlWzdh5ZOnZZdIXm8R87hywf53Wuox8+SwHMmOE1cGI0rOgIrX4ruwwNfX9A62Uq7YauSJ5Jz8FYiAT61e8s5ZADMiQVUzLD/F5t+iQ+kmviGnGSxDistg3pUqWbSU3v71igFRnhpJ5AE+bagA9QOgdVV9kbphfHahdmEq22eWtYV1rhW5VeuCdBgpEP1YLCg04OalF0+gGxV7Sqw0AevAMXS3AEv2l4faxXTEcfd7Jz6LVWTJP8JkZ4uZWhH0yFcgiMBtXExtme84lOIVl+XuuU8dQpDftXotWcPuRKtuEYZ0WvrPWWrM0QrpVvKAh89LluhYePI/479qRYd/BSEGLN4dqcOwHtCEQNc88m4XwQj3++jX6RoyAbP7W9P2CJ5GxchIEZvf+mtlVnLJDX6xAOmO/N/CfLTzolkoExo+aVPWpfjRt2gxttFS1zTORgAQqiVBBoQ04B5BfNNHClsFavLjIgkrOn6Zke9NfffSmMwgmyBF65Geml0mNVBtitSnT2OzGsEG1DX121YKmQDZX4EDw=
  template:
    metadata:
      name: stockchartsalerts-secrets
      namespace: stockchartsalerts
