---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: https://envoyproxy.github.io/gateway-helm
