---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - tcp-services-configmap.yaml
  - default-backend-deployment.yaml
  - default-backend-ingress.yaml
