---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  # Expose PostgreSQL on port 5432
  # Format: "external-port": "namespace/service:internal-port"
  "5432": "postgres/postgres-rw:5432"
