---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - sealed-secret-default.yaml  # Creates clickhouse-credentials secret
  - ingress.yaml
