---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  interval: 30m
  chart:
    spec:
      chart: clickhouse
      version: '0.3.1'
      sourceRef:
        kind: HelmRepository
        name: altinity
        namespace: clickhouse
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    clickhouse:
      # Default user (required by ClickHouse) - restricted to localhost only
      defaultUser:
        password_secret_name: "clickhouse-default-auth"  # Separate secret for default user
        allowExternalAccess: false  # Restrict to localhost
        hostIP: "127.0.0.1/32"  # Localhost only

      # Custom admin user with full privileges
      users:
        - name: major
          hostIP: ["0.0.0.0/0"]  # Allow from anywhere
          accessManagement: 1  # Full admin privileges
          password_secret_name: "clickhouse-major-auth"  # Separate secret for major user
          grants:
            - "GRANT ALL ON *.*"  # Full access to all databases

      # Persistent storage configuration
      persistence:
        enabled: true
        size: 20Gi  # Match old setup
        accessMode: ReadWriteOnce
        storageClass: ""  # Use default storage class
        logs:
          enabled: true
          size: 5Gi  # Match old setup for logs
          accessMode: ReadWriteOnce

      # Service configuration - use ClusterIP for internal access
      service:
        type: ClusterIP
        serviceAnnotations: {}
        serviceLabels:
          app: clickhouse

      # Performance settings optimized for analytical queries
      configOverride:
        max_concurrent_queries: 100
        max_connections: 1000
        max_memory_usage: 10000000000  # 10GB
        max_bytes_before_external_group_by: 5000000000  # 5GB

        # Compression for storage efficiency
        compression:
          case:
            method: lz4

        # Logging configuration
        logger:
          level: trace
          console: true
          size: 100M
          count: 3

      # Resource limits - match old setup
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "4Gi"
          cpu: "2000m"

    # Disable Keeper for single-node setup (we don't need clustering yet)
    keeper:
      enabled: false

    # Disable operator for now (simpler setup)
    operator:
      enabled: false
