---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-auth
  namespace: clickhouse
spec:
  encryptedData:
    admin-password: AgA/MKD/samfB+y8K1YfnvIk6bYcHcbJeotTsWJLeXsrSeh7m3O9Aj83m8UXh4BZoA7mDK/XctQwkm0R44uuIbIAAigrL1iOzacjlsuQt1hMVp5TJKlam3dBdelY/ovIMWeMLex8tPinHgyWID9mnc8qkkVvX4f1Q1hUzGkZns2CK5otrjEbmJNkIrF6t0SWeoyF99Dzt/2rcLVNzi+Vkx9gG9eBfmsmUz3TZh94wVNwIGtCpl3FzAhyVQfvR22oUfhhYKQ1MfDH1EwY0yteRXGukTallruR8HGafYTpHYDR+8qu5wWy3JUdg8J7lzOW5gxJRETOPc1WqlgN/NnY7QHcAK/xdLSdGpHvVKnOLlsNr0YpuOnprjJcfarP8QkST3AxWm27ADXJhSjKDskcI7JiZTYuigwL6Pt3RhXhVnk8dzWqg4svFYXG8+wuyVJs5lsONKrCJ6sgWgSj0jXedh0pqs+TVF9/M2pfX1YMSZt3MT+7viPz0nqQv30ZLd5n5j4ehrmmG1FSjzP91F2ZlQjQTElNAXn5Khte2kvjACu3NeMlf5/nH9CPD7jZhoWTdstIkobJLb0UDFgaq07nS+bAgEBkZ2zWrE1+UPzSpIcgHQAKyowOMu1f6OYCPE9qZHua8bQMg9HzNwjLKSiDDye2Z6F5DT6dUiLLQ+39OhvYIHLvWrTD+EDLI2kZdsaOv1PqLUMxu9lvLHNGAlHfvGz3Rzr4aw==
    admin-user: AgCNq14FfjqTfhScA2mB1VRDhdKldQzgCU8xjmO+CWOFG3DTJLgNWBlMh1hdj/a5r3THlWpPe6HGz74QQyXxi9UJ/7q/3CInTA5Pd+r7FlnTvufPp1+1JfgyZi9kIxxqRHiKmoJ1PAh3cBxbKOFxNUtoQwtNsqwmUuNu9qPcaj6POH6/M2vCrrUuNDYOcwBQYQa7sX3x3pcf5aPrSMoPoVIU/IjZ/rCLQeaLXVsWfTk2qGwYDuYqu863T/hNubKH2HSsiGL9NuO9APBtuqhuHS5tg5xn8bWmavU9GABzo0+QEAdS1eeX3sf6gwFjCguo0AQqBrhULIueJB2j/G2I5fOaPIk/hI4vA5Ctftqk5ShWFJroadokzI23F1VwXge2e2RLYuRaJhy3Xs3je2EPnQpxvCd0fs3QMfn5DhS4KL/LFqMBoNjiCnDJ3IASNZmWkL36fg3+Z+4VHb6KQvQF872M0kj/v3QPZZTImf8syJqaK3WLwyDoxux0W6GFzddkg2FLo+oYNZspt5W2ZAPnd59+ApD1h3kgpHQiQYE1ut8rFI0LYZ+rKG+bQWrNRHoirJKcOIwSqD1BvRhL2ctkA5VT81hpfwnNs19Czow+dewifbNKq33WaMItKo1jbWwZI9Kd8o/UHXySnYdvMImdtsBwidbYYVPQ/DsmWt4UFhHZGZSMsNoZ9QYu/jaDJwoBRsYPhDQsow==
  template:
    metadata:
      name: clickhouse-auth
      namespace: clickhouse
