# Template for creating the clickhouse auth secrets
# Each user needs a separate secret with a 'password' key
#
# After updating the password values below, seal them with:
#
# kubectl --kubeconfig ~/.kube/k3s-psychz-config create secret generic clickhouse-default-auth \
#   --from-literal=password=YOUR_DEFAULT_USER_PASSWORD \
#   --namespace=clickhouse \
#   --dry-run=client -o yaml | \
# kubeseal --kubeconfig ~/.kube/k3s-psychz-config \
#   --controller-name=sealed-secrets \
#   --controller-namespace=sealed-secrets \
#   --format=yaml > apps/base/clickhouse/sealed-secret-default.yaml
#
# kubectl --kubeconfig ~/.kube/k3s-psychz-config create secret generic clickhouse-major-auth \
#   --from-literal=password=YOUR_MAJOR_USER_PASSWORD \
#   --namespace=clickhouse \
#   --dry-run=client -o yaml | \
# kubeseal --kubeconfig ~/.kube/k3s-psychz-config \
#   --controller-name=sealed-secrets \
#   --controller-namespace=sealed-secrets \
#   --format=yaml > apps/base/clickhouse/sealed-secret-major.yaml

---
# Secret for 'default' user (restricted, localhost only)
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-default-auth
  namespace: clickhouse
type: Opaque
stringData:
  password: "REPLACE_WITH_DEFAULT_USER_PASSWORD"
---
# Secret for 'major' user (admin, full access)
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-major-auth
  namespace: clickhouse
type: Opaque
stringData:
  password: "REPLACE_WITH_MAJOR_USER_PASSWORD"
