---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: ghcr.io/librespeed/speedtest:latest@sha256:6204c871fbd3e79af0d65ea15e669119122bb8b1d40e4ed2db8c0fe849d634f1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
