---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: '>=31.0.0 <32.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 1

    # Port configuration
    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        # Redirect HTTP to HTTPS
        redirectTo:
          port: websecure
      websecure:
        port: 443
        expose:
          default: true
        exposedPort: 443
        tls:
          enabled: true
          certResolver: porkbun

    # Certificate resolvers
    certResolvers:
      porkbun:
        acme:
          email: your-email@example.com  # CHANGE THIS
          storage: /data/acme.json
          dnsChallenge:
            provider: porkbun
            resolvers:
              - 1.1.1.1:53
              - 8.8.8.8:53

    # Environment variables from sealed secret
    envFrom:
      - secretRef:
          name: porkbun-credentials

    # Persistence for ACME certificates
    persistence:
      enabled: true
      size: 128Mi

    # Service configuration
    service:
      type: LoadBalancer

    # Enable dashboard (accessible internally)
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.localhost`)
        entryPoints: ["web"]

    # Logging
    logs:
      general:
        level: INFO
      access:
        enabled: true
