---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: '<38.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 1

    # Port configuration
    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        # Redirect HTTP to HTTPS
        redirectTo:
          port: websecure
      websecure:
        port: 443
        expose:
          default: true
        exposedPort: 443
        tls:
          enabled: true
          certResolver: porkbun

    # Certificate resolvers configuration via CLI arguments
    additionalArguments:
      - "--certificatesresolvers.porkbun.acme.email=major@mhtx.net"
      - "--certificatesresolvers.porkbun.acme.storage=/data/acme.json"
      - "--certificatesresolvers.porkbun.acme.dnschallenge=true"
      - "--certificatesresolvers.porkbun.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.porkbun.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

    # Environment variables from sealed secret
    env:
      - name: PORKBUN_API_KEY
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: PORKBUN_API_KEY
      - name: PORKBUN_SECRET_API_KEY
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: PORKBUN_SECRET_API_KEY

    # Persistence for ACME certificates
    persistence:
      enabled: true
      size: 128Mi

    # Service configuration
    service:
      type: LoadBalancer

    # Enable dashboard (accessible via custom IngressRoute)
    ingressRoute:
      dashboard:
        enabled: false

    # Logging
    logs:
      general:
        level: INFO
      access:
        enabled: true
