---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: '>=31.0.0 <32.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 1

    # HTTP only configuration
    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
      websecure:
        expose:
          default: false

    # Service configuration
    service:
      type: LoadBalancer

    # Enable dashboard (accessible internally)
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.localhost`)
        entryPoints: ["web"]

    # Logging
    logs:
      general:
        level: INFO
      access:
        enabled: true
