---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./deploy/porkbun-webhook
      sourceRef:
        kind: GitRepository
        name: porkbun-webhook
        namespace: flux-system
      interval: 12h
  targetNamespace: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: porkbun-webhook
    groupName: acme.amajor.cloud

    image:
      repository: ghcr.io/mdonoughe/porkbun-webhook
      tag: v0.1.5@sha256:0d27faf2203801abb9c0cf5c887dea978a7d8eb92ddc2278eff8b2e92105e8e9
      pullPolicy: IfNotPresent

    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
