---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCP4uexhzKTcJEWy8WER45p7pN6XxsAOE4nkzOFsXD9EyMowsRHfiqyuobnFM5HmcI7XRA89SaQnHPw6fomHgHtUk2EnN1NtF/1gZbrduou2gRdNRRupDtfQ8hagpLUY5ds9it2sMY/JoV7RhbfCkG/pZ+2BRqle/T3x0B23t7WxC1OqTLV+6iTqJ77t/5SbcNzgdmq6t3zumy8jJBF67XIHBtjSLWzqDeZdn6QmweZdi7JSxCckRwpYTqNeXap46PRoTOzkzDIC8fzkWu9Tt8qAWZcCwLh1Sl3EF0mAj+Nt/0X6g2WHQOB7E+hDNJJ9RuRlNcUwF4Nt/MOhLa907MwRtm2x+DZYlDjiIMJt505rzbgykpDwCsfkexFEo/t7Z3m8jCr0vXGyD9V2id2eLoA4Ws+dqt2bhQYHyOam/cMcJWrjHAC/tVPK6xNHWf+gkx2/MaFC8eoUp6i0u/rH/0RmXk/Az1pWIAib8OkQzDXmxWM5sbHTHfvOWoZxI1cGJ9NF2S15w7zHKoFAv6xxivMIKMqhC+FmZxzMO/GAv3EG/ImXn68kWEK9lAu4LixQnxdqIKsNtD9Opf1Te/HTqWzEkbUm3UL0DMu6G90bvfIamOzav6/IVATzSGoWGaAXiqCdRGCCct0bU5Ebh0ZGmVHWIqtxaLoLWfWQ58B5G93BPbXwHorwrmuddbVIaCSOAn0joaCJZszzU14M167VEqU4Q4xMtp5bcZA8F4NyYkbOhGBf0lANc04Fse22w==
  template:
    metadata:
      name: webhook-token
      namespace: flux-system
