---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:latest@sha256:951ca254f7caa23cc9d417a90b74efc4b76efd896f2ce63d56ff00e7fd168e32
          ports:
            - containerPort: 8080
          env:
            - name: GATUS_CONFIG_PATH
              value: /config/config.yaml
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: discord-webhook
                  key: url
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: gatus-config
      terminationGracePeriodSeconds: 5
