---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: '37.1.2'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 1

    # Port configuration
    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        # Redirect HTTP to HTTPS
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
        expose:
          default: true
        exposedPort: 443
        tls:
          enabled: true

    # Persistence for ACME certificates
    persistence:
      enabled: true
      name: traefik-acme
      size: 128Mi
      path: /data
      accessMode: ReadWriteOnce

    # Certificate resolvers
    certResolvers:
      porkbun:
        acme:
          email: major@mhtx.net
          storage: /data/acme.json
          dnsChallenge:
            provider: porkbun
            delayBeforeCheck: 30
            resolvers:
              - 1.1.1.1:53
              - 8.8.8.8:53

    # Environment variables for Porkbun API credentials
    env:
      - name: PORKBUN_API_KEY
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: api-key
      - name: PORKBUN_SECRET_API_KEY
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: secret-api-key

    # Service configuration
    service:
      type: LoadBalancer

    # Enable dashboard (accessible via custom IngressRoute)
    ingressRoute:
      dashboard:
        enabled: false

    # Logging
    logs:
      general:
        level: INFO
      access:
        enabled: true
