---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: '37.1.2'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 1

    # Port configuration
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        # Redirect HTTP to HTTPS
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        tls:
          enabled: true

    # Service configuration
    service:
      enabled: true
      type: LoadBalancer

    # Disable dashboard IngressRoute (manage separately if needed)
    ingressRoute:
      dashboard:
        enabled: false

    # Logging
    logs:
      general:
        level: INFO
      access:
        enabled: true
