---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 10m
  chart:
    spec:
      chart: uptime-kuma
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: uptime-kuma
  values:
    # Persistence for Uptime Kuma data
    persistence:
      enabled: true
      size: 4Gi

    # Service configuration
    service:
      type: ClusterIP
      port: 3001
