---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.1
  ignore: |
    /*
    !/config/crd
