---
# ЁЯЪи Alert for Kustomization errors/failures only
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kustomizations
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: flux-system
  summary: "тЪая╕П Flux Kustomization Error"
---
# ЁЯЪи Alert for HelmRelease errors/failures only
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: '*'
  summary: "тЪая╕П Flux HelmRelease Error"
