---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgAWZW1gdM3SiTz7qIt+yLuZnOdLE3kNmJh11bhfBz+HQGaH+aGzg5+fOG6jXtxkBo35QMMg4hW+CIDfi7vsxVMCY16hgScPqVd78VXgIESikXMmU8btdaOEXyFdTa6jn3Xk91SERBr5Ki6mUcOdQaNIEUccbxtTa8G53TbXyGBRFljMcxHtgfzI1RjqkPnf4eH1pX9+HUv5EOV+G8kBnhztqs1LM9LzamzgN/jyDHdnEfAgd3abuLKuG9FZmaYW4aCMAYWnxPpOP6g8KoZzSC67HrXWODRxxmozhx8t2AmS2Ym0DLALARmHE0YvCmnHxCJ8B1SNOZxXt1X+5tmi9L/C5uzBjAuaAWYmfWBT97iF738KeCRtSZkTP1QfZj3uLY2kPLC4hk7Qe5dC0y/g1fJX60WPmdOYvOnKjPgPHOKsN9YbTTZ6cigpOxu7PvidIng4OYyV3TCTTx27OjQg6VsQSGDu/zdm4+Tb25JH+RXOZHUuPsf0MxzlD5trcc/h0R+2BONrtkpU+Hl8cRqmk5nQPUmaCKCEIYy387A+gsq1CmHCYPoj0ojcONEUCdug9yuIzi3bOilhPLUDZStcCIjVcLxyvfR0bXpa/bNyf6yNl0KT0HUe8fLB7GY90DDawCVpcl/K2FvpItnnDHRR0NDOWZPX8r5dP2p4QMWOaBiGDPhhPK8zSl8cT0oymQyYyAc5BGw4JhNyD1LMo2/i3WMlI9mxflmoCHIa6t3PUIRNcn7xvKjJzI3mE5F++kvzL+UIYp7xpwKoZMf/dwDpIkCCExyCm/R7QM8DTkd7HlScWOpmENG0rvutAs6jrWffe8y4HIkPNtMZvpSCViWjH7AAVtKWa7KhE4gB
  template:
    metadata:
      name: discord-webhook
      namespace: flux-system
