# 🔐 Template for Discord webhook secret
#
# Replace YOUR_DISCORD_WEBHOOK_URL with your actual Discord webhook URL
# Then seal this secret using kubeseal:
#
# kubectl --kubeconfig ~/.kube/k3s-config create secret generic discord-webhook \
#   --from-literal=address=YOUR_DISCORD_WEBHOOK_URL \
#   --namespace=flux-system \
#   --dry-run=client -o yaml | \
# kubeseal --kubeconfig ~/.kube/k3s-config \
#   --controller-name=sealed-secrets \
#   --controller-namespace=sealed-secrets \
#   --format=yaml > apps/infra/flux-notifications/discord-webhook-sealed-secret.yaml
#
# Then delete this template file and commit the sealed secret.

apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
type: Opaque
stringData:
  address: "YOUR_DISCORD_WEBHOOK_URL"
