---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns01
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: major@mhtx.net
    privateKeySecretRef:
      name: letsencrypt-staging-dns01-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.amajor.cloud
          solverName: porkbun
          config:
            apiKeySecretRef:
              name: porkbun-credentials
              key: PORKBUN_API_KEY
            secretKeySecretRef:
              name: porkbun-credentials
              key: PORKBUN_SECRET_API_KEY
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: major@mhtx.net
    privateKeySecretRef:
      name: letsencrypt-production-dns01-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.amajor.cloud
          solverName: porkbun
          config:
            apiKeySecretRef:
              name: porkbun-credentials
              key: PORKBUN_API_KEY
            secretKeySecretRef:
              name: porkbun-credentials
              key: PORKBUN_SECRET_API_KEY
