---
# Grants porkbun-webhook ServiceAccount read access to porkbun-credentials secret.
# The upstream Helm chart creates the ServiceAccount but does not grant secret permissions.
# This manual RBAC is required for the webhook to authenticate with Porkbun API.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-webhook-secret-reader
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["porkbun-credentials"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook-secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-webhook-secret-reader
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
